### ISSUE TITLE
Invalid argument(s): Illegal character in path  

### ISSUE THREAD

**Issue by craftbox2442** [gotamafandy/flutter_shareable#1]
Oops; flutter has exited unexpectedly: "Invalid argument(s): Illegal character in path".
A crash report has been written to D:\Flutter project\flutter_shareable_demo\angular\flutter_02.log.

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --track-widget-creation --device-id=chrome web\main.dart

## exception

ArgumentError: Invalid argument(s): Illegal character in path

```
#0      _Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:1732:11)
#1      _Uri._makeWindowsFileUrl (dart:core/uri.dart:1825:7)
#2      new _Uri.file (dart:core/uri.dart:1700:11)
#3      DefaultResidentCompiler._doMapFilename (package:flutter_tools/src/compile.dart:846:18)
#4      DefaultResidentCompiler._mapFilename (package:flutter_tools/src/compile.dart:815:12)
#5      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:604:9)
#6      _RecompileRequest._run (package:flutter_tools/src/compile.dart:408:16)
#7      _CompilationRequest.run (package:flutter_tools/src/compile.dart:388:30)
#8      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:638:23)
#9      _rootRunUnary (dart:async/zone.dart:1134:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#14     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#16     _rootRun (dart:async/zone.dart:1122:38)
#17     _CustomZone.run (dart:async/zone.dart:1023:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.15.21-pre.35, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.15.21-pre.35 at D:\flutter_windows_v1.9.1+hotfix.4-stable\flutter
    • Framework revision fd82ef06bd (12 days ago), 2020-03-13 01:01:02 -0400
    • Engine revision 85e6b01ae2
    • Dart version 2.8.0 (build 2.8.0-dev.14.0 7c2f62406b)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:/sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 2.2)
    • Android Studio at D:\android studio2.2
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_76-release-b03)

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] Connected device (3 available)
    • XT1706     • HKE69SQ1   • android-arm    • Android 6.0 (API 23)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

**Comment by craftbox2442** [comment]
solved
